package com.zhekasmirnov.innercore.optifine_api;

public class InitClasses {
   public static void init(){
       JsAdaptedScriptAPILevel.init();
       JsNativeTileEntity.init();
       JsNativeCompoundTag.init();
       JsNativeListTag.init();
       JsNativeItemInstance.init();
       JsAdaptedScriptAPIEntity.init();
       JsNativePathNavigation.init();
       JsNativeAttributeInstance.init();
       JsAdaptedScriptAPITranslation.init();
       JsAdaptedScriptAPIUpdatable.init();
       JsAdaptedScriptAPIParticles.init();
       JsParticleRegistryParticleType.init();
       JsAdaptedScriptAPIGenerationUtils.init();
       JsAdaptedScriptAPIPlayer.init();
       JsAdaptedScriptAPIIDRegistry.init();
       JsAdaptedScriptAPIRecipes.init();
       JsWorkbenchShapelessRecipe.init();
       JsRecipeEntry.init();
       JsWorkbenchShapedRecipe.init();
       JsNativeBlockSource.init();
       JsBlockBreakResult.init();
       JsBlockState.init();
       JsAdaptedScriptAPIUI.init();
       JsFrameTexture.init();
       JsUIWindowLocation.init();
       JsUIStyle.init();
       JsUIWindow.init();
       JsContentProvider.init();
       JsAdaptedScriptAPIBlock.init();
       JsAdaptedScriptAPIItem.init();
       JsNativeItem.init();
       JsAdaptedScriptAPIGameController.init();
       JsAdaptedScriptAPISaver.init();
       JsAdaptedScriptAPILogger.init();
       JsAdaptedScriptAPIPlayerActor.init();
       JsItemStack.init();
       JsNativeItemModel.init();
       JsNativeShaderUniformSet.init();
       JsGuiBlockModel.init();
       JsGuiBlockModelBox.init();
       JsBlockShape.init();
       JsGuiRenderMesh.init();
       JsNativeRenderMesh.init();
       JsNativeRenderMeshReadOnlyVertexData.init();
       JsAdaptedScriptAPIItemContainer.init();
       JsContainer.init();
       JsItemContainerSlot.init();
       JsItemContainer.init();
       JsNetworkEntity.init();
       JsConnectedClientList.init();
       JsNetworkEntityType.init();
       JsItemContainerUiHandler.init();
       JsNativeItemInstanceExtra.init();
   }
}
